swagger: '2.0'
info:
  title: API de Red Social
  description: Documentación de la API para la red social
  version: 1.0.0
host: localhost:3001
basePath: /
tags:
  - name: Users
  - name: Tags
  - name: Posts
  - name: Comments
  - name: Archives
  - name: Post Tag
  - name: Post Image
schemes:
  - http
paths:
  /users:
    get:
      tags:
        - Users
      description: ''
      responses:
        '200':
          description: OK
        '204':
          description: No Content
    post:
      tags:
        - Users
      description: ''
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              nickName:
                example: any
              email:
                example: any
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
  /users/{id}:
    get:
      tags:
        - Users
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    put:
      tags:
        - Users
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    delete:
      tags:
        - Users
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
  /comments:
    get:
      tags:
        - Comments
      description: ''
      responses:
        '200':
          description: OK
    post:
      tags:
        - Comments
      description: ''
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              postId:
                example: any
              userId:
                example: any
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
  /comments/{id}:
    get:
      tags:
        - Comments
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    put:
      tags:
        - Comments
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    delete:
      tags:
        - Comments
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
  /posts:
    get:
      tags:
        - Posts
      description: ''
      responses:
        '200':
          description: OK
        '204':
          description: No Content
    post:
      tags:
        - Posts
      description: ''
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              userId:
                example: any
      responses:
        '201':
          description: Created
  /posts/{id}:
    get:
      tags:
        - Posts
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    put:
      tags:
        - Posts
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: body
          in: body
          schema:
            type: object
            properties:
              userId:
                example: any
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    delete:
      tags:
        - Posts
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
  /posts/{postId}/tags/{tagId}:
    post:
      tags:
        - Post Tag
      description: ''
      parameters:
        - name: postId
          in: path
          required: true
          type: string
        - name: tagId
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
    delete:
      tags:
        - Post Tag
      description: ''
      parameters:
        - name: postId
          in: path
          required: true
          type: string
        - name: tagId
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
  /posts/{postId}/tags/{id}:
    delete:
      tags:
        - Post Image
      description: ''
      parameters:
        - name: postId
          in: path
          required: true
          type: string
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '404':
          description: Not Found
    put:
      tags:
        - Post Image
      description: ''
      parameters:
        - name: postId
          in: path
          required: true
          type: string
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '404':
          description: Not Found
  /tags:
    get:
      tags:
        - Tags
      description: ''
      responses:
        '200':
          description: OK
        '204':
          description: No Content
    post:
      tags:
        - Tags
      description: ''
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              tag:
                example: any
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
  /tags/{id}:
    get:
      tags:
        - Tags
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    put:
      tags:
        - Tags
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    delete:
      tags:
        - Tags
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
  /archives/:
    get:
      description: ''
      responses:
        '200':
          description: OK
    post:
      description: ''
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              postId:
                example: any
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /archives/{id}:
    put:
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    delete:
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /:
    get:
      description: ''
      responses:
        '200':
          description: OK
    post:
      description: ''
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              postId:
                example: any
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /{id}:
    put:
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    delete:
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
