swagger: '2.0'
info:
  title: API de Red Social
  description: Documentación de la API para la red social
  version: 1.0.0
host: localhost:3001
basePath: /
tags:
  - name: Users
  - name: Tags
  - name: Posts
  - name: Comments
  - name: Archives
  - name: Post Tag
  - name: Post Image
schemes:
  - http
paths:
  /users:
    get:
      tags:
        - Users
      description: ''
      responses:
        '200':
          description: OK
    post:
      tags:
        - Users
      description: ''
      parameters:
        - name: body
          in: body
          description: Datos del usuario
          required: true
          schema:
            $ref: '#/definitions/UserInput'
      responses:
        '201':
          description: Created
  /users/{id}:
    get:
      tags:
        - Users
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
    put:
      tags:
        - Users
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: body
          in: body
          description: Datos del usuario
          required: true
          schema:
            $ref: '#/definitions/UserInput'
      responses:
        '200':
          description: OK
    delete:
      tags:
        - Users
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
  /comments:
    get:
      tags:
        - Comments
      description: ''
      responses:
        '200':
          description: OK
    post:
      tags:
        - Comments
      description: ''
      parameters:
        - name: body
          in: body
          description: Datos del comentario (userId, postId y content)
          required: true
          schema:
            $ref: '#/definitions/CommentInput'
      responses:
        '201':
          description: Created
  /comments/{id}:
    get:
      tags:
        - Comments
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
    put:
      tags:
        - Comments
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: body
          in: body
          description: Solo el contenido del comentario
          required: true
          schema:
            $ref: '#/definitions/CommentUpdateInput'
      responses:
        '200':
          description: OK
    delete:
      tags:
        - Comments
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
  /posts:
    get:
      tags:
        - Posts
      description: ''
      responses:
        '200':
          description: OK
    post:
      tags:
        - Posts
      description: ''
      parameters:
        - name: body
          in: body
          description: Datos del post (userId y content)
          required: true
          schema:
            $ref: '#/definitions/PostInput'
      responses:
        '201':
          description: Created
  /posts/{id}:
    get:
      tags:
        - Posts
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
    put:
      tags:
        - Posts
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: body
          in: body
          description: Solo el contenido del post
          required: true
          schema:
            $ref: '#/definitions/PostUpdateInput'
      responses:
        '200':
          description: OK
    delete:
      tags:
        - Posts
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
  /posts/{postId}/tags/{tagId}:
    post:
      tags:
        - Post Tag
      description: ''
      parameters:
        - name: postId
          in: path
          required: true
          type: string
        - name: tagId
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
    delete:
      tags:
        - Post Tag
      description: ''
      parameters:
        - name: postId
          in: path
          required: true
          type: string
        - name: tagId
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
  /posts/{postId}/archives/{id}:
    delete:
      tags:
        - Post Image
      description: ''
      parameters:
        - name: postId
          in: path
          required: true
          type: string
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    put:
      tags:
        - Post Image
      description: ''
      parameters:
        - name: postId
          in: path
          required: true
          type: string
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
  /tags:
    get:
      tags:
        - Tags
      description: ''
      responses:
        '200':
          description: OK
    post:
      tags:
        - Tags
      description: ''
      parameters:
        - name: body
          in: body
          description: Datos del tag
          required: true
          schema:
            $ref: '#/definitions/TagInput'
      responses:
        '201':
          description: Created
  /tags/{id}:
    get:
      tags:
        - Tags
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
    put:
      tags:
        - Tags
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: body
          in: body
          description: Datos del tag
          required: true
          schema:
            $ref: '#/definitions/TagInput'
      responses:
        '200':
          description: OK
    delete:
      tags:
        - Tags
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
  /archives:
    get:
      tags:
        - Archives
      description: ''
      responses:
        '200':
          description: OK
    post:
      tags:
        - Archives
      description: ''
      consumes:
        - multipart/form-data
      parameters:
        - name: postId
          in: formData
          type: string
          description: ID del post al que pertenece el archivo
          required: true
        - name: file
          in: formData
          type: file
          description: Archivo a subir
          required: true
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
  /archives/{id}:
    put:
      tags:
        - Archives
      description: ''
      consumes:
        - multipart/form-data
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: file
          in: formData
          type: file
          description: Archivo a subir
          required: true
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
    delete:
      tags:
        - Archives
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
definitions:
  UserInput:
    type: object
    properties:
      nickName:
        type: string
        example: ejemploNick
      email:
        type: string
        example: ejemplo@email.com
  TagInput:
    type: object
    properties:
      nameTag:
        type: string
        example: ejemploTag
  PostInput:
    type: object
    properties:
      userId:
        type: string
        example: id de usuario
      content:
        type: string
        example: Contenido del post
  PostUpdateInput:
    type: object
    properties:
      content:
        type: string
        example: Contenido del post
  CommentInput:
    type: object
    properties:
      userId:
        type: string
        example: id de usuario
      postId:
        type: string
        example: id del post
      content:
        type: string
        example: Contenido del comentario
  CommentUpdateInput:
    type: object
    properties:
      content:
        type: string
        example: Contenido del comentario
